name: Upload Website

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: S3 Deploy
    uses: Reggionick/s3-deploy@v3.1.1
    with:
    # Directory to deploy
    folder: ./public
    # Name of AWS Bucket
    bucket: soleymanshahir.com
    # The destination bucket region
    bucket-region: eu-west-2

    # - uses: actions/checkout@master
    #   uses: jakejarvis/s3-sync-action@v0.5.1
    #     with:
    #     args: --acl public-read --follow-symlinks --delete --exclude '.git/*'
    #   env:
    #     AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
    #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     AWS_REGION: 'eu-west-2'   # optional: defaults to us-east-1
    #     SOURCE_DIR: 'public'      # optional: defaults to entire repository
